### ISSUE TITLE
Broken URL in Lilypad CLI resulting in `LATEST_GIT_HASH: unbound variable`

### ISSUE THREAD

**Issue by jochasinga** [bacalhau-project/lilypad-modicum#77]
https://github.com/bacalhau-project/lilypad-modicum/blob/ab46722146128dda8c29695242bf03d0e0203e72/lilypad#L10

The Github URL leads to 404 not found. The repo needs to change from "lilypad" to "lilypad-modicum".

```bash
LATEST_TXT="$(curl -sSL https://raw.githubusercontent.com/bacalhau-project/lilypad-modicum/main/latest.txt)"
```

**Comment by binocarlos** [comment]
@jochasinga thanks for bug report - this was my fault because I renamed the repo and didn't update the install script

We've just pushed a fix to this and the docs so it should be working OK now...
