### ISSUE TITLE
CLI simply 404?

### ISSUE THREAD

**Issue by mahavatara** [bacalhau-project/lilypad-modicum#79]
The project seems to be alive, but the curl line that's supposed to get the cli gives me a 404 for https://bit.ly/get-lilypad
What's going on !

**Comment by DeveloperAlly** [comment]
Here is the CLI install line 

curl -sSL -O https://raw.githubusercontent.com/bacalhau-project/lilypad-modicum/main/lilypad && sudo install lilypad /usr/local/bin/lilypad

from the docs: https://docs.lilypadnetwork.org/lilypad-v1-testnet/quick-start/install-run-requirements

**Comment by mahavatara** [comment]
> curl -sSL -O https://raw.githubusercontent.com/bacalhau-project/lilypad-modicum/main/lilypad

Thanks. I guess you know where I found the shurl :)
